version: 0.0 
os: linux 
files:
  - source: helloworld.js
    destination: /usr/local/helloworld/
  - source: helloworld.service
    destination: /etc/systemd/system/
hooks: 
  BeforeInstall: 
    - location: stop.sh 
      timeout: 30 
  ApplicationStart:
    - location: start.sh
      timeout: 30
  ValidateService:
    - location: validate.sh
